# version: "3"  # Specify the version of Docker Compose

services:
  # Builds the frontend Docker image and creates the frontend microservice
  frontend:
    image: myronkip/yolo-frontend:v1.0.5
    # build: ./client
    container_name: yolo-frontend
    ports:
      - "80:80"
    depends_on: 
      - backend
    networks:
      - app_net

  # Builds the backend Docker image and creates the backend microservice
  backend:
    image: myronkip/yolo-backend:v1.0.3
    # build: ./backend
    container_name: yolo-backend
    restart: always
    ports:
      - "5000:5000"
    depends_on: 
      - mongo
    networks:
      - app_net

  # Creates the database microservice
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - app_net
    volumes:
      - app_mongo_data:/data/db  # Use the named volume directly

# Creates the network infrastructure necessary for the containers to communicate with each other
networks:
  app_net:
    driver: bridge

# Creates a Docker volume that persists all the data stored in the database
volumes:
  app_mongo_data:
