---
- name: Run MongoDB Container
  docker_container:
    name: mongo
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - app_mongo_data:/data/db
    networks:
      - name: app_net
  tags:
    - database
    - backend