---
- name: Pull image from repository
  docker_image:
    name: brianbwire/brian-yolo-backend:v1.0.0
    source: pull
---
- name: Pull image from repository
  docker_image:
    name: myronkip/yolo-backend:v1.0.1
    source: pull

- name: Create Node.js Backend Container
  docker_container:
    name: yolo-backend
    image: myronkip/yolo-backend:v1.0.1
    networks:
      - name: app-net
    ports:
      - "5000:5000"
    command: "npm start"
  become: yes
- name: Create Node.js Backend Container
  docker_container:
    name: brian-yolo-backend
    image: brianbwire/brian-yolo-backend:v1.0.0
    networks:
      - name: app-net
    ports:
      - "5000:5000"
    command: "npm start"
  become: yes