---
- name: Clone the backend repository
  git:
    repo: "{{ repo_url }}"
    dest: /opt/yolo-backend
    version: 'test'  

- name: Pull image from repository
  docker_image:
    name: "{{ docker_image }}"
    source: pull

- name: Create Node.js Backend Container
  docker_container:
    name: "{{ container_name }}"
    image: "{{ docker_image }}"
    networks:
      - name: "{{ network }}"
    ports:
      - "5000:5000"
    command: "npm start"
  become: yes